# @api = http://127.0.0.1:51202/books
@api = http://dev.mofunc.com/ws/books

### get books
GET {{api}}
content-type: application/json

### get 完本 books
GET {{api}}?q={"status": "完本"}
content-type: application/json

### get books
GET {{api}}/3714
content-type: application/json

### get sections
GET {{api}}/3714/sections
content-type: application/json

### get a section
GET {{api}}/sections/2805718/contents
content-type: application/json

### insert a content
POST {{api}}/contents
content-type: application/json

{
	"section":27,
	"contents":"2166271 \"n\\'\\'contents"
}