export = `
CREATE TABLE IF NOT EXISTS sites (
	id INT UNSIGNED AUTO_INCREMENT,
	book INT,
	title VARCHAR(100),
	prev INT COMMENT '上一章',
	next INT COMMENT '下一章',
	contents LONGTEXT,
	createdAt datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	updatedAt timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (id),
	FOREIGN KEY (book) REFERENCES books(id),
	FOREIGN KEY (prev) REFERENCES sections(id),
	FOREIGN KEY (next) REFERENCES sections(id)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
`;
